issues 14 (Уведомления картинки)
orioks-monitoring/bot pull request #16
Opened 2022-04-07 08:36 UTC by Whom-m0rty

Итак, я сломал вам requirements.txt не принимайте это в репозиторий.

Юзабилити можете найти в images/test.py

Все вопросы по коду/рефактору обсуждаются)

2022-04-09 21:23 UTC, Whom-m0rty commented
Nu sho tam....

2022-04-09 21:29 UTC, llirrikk commented
Завтра что-нибудь сделаю, сори за задержку

2022-04-09 21:30 UTC, Whom-m0rty commented
Да все хорошо, просто думал, что мб что-то не так...

2022-04-10 19:56 UTC, llirrikk requested changes

2022-04-10 19:56 UTC, llirrikk commented on images/imager.py
> +        self.image.paste(img, (int((self.image_weight - img.pixel_size) / 2), int(offset)))
```python
int(a / b) == a // b
```
для неотрицательных

2022-04-10 19:56 UTC, llirrikk commented on images/imager.py
> +            max_grade: int,
вполне вероятно могут быть и `float`

2022-04-10 19:56 UTC, llirrikk commented on images/imager.py
> +    font_downer = ImageFont.truetype('source/PTSansCaption-Bold.ttf', size=62)
Предлагаю для совместимости заменить все разделители в `str`, используя `os.path.join` (https://docs.python.org/3/library/os.path.html#os.path.join) и заменить тип путей на `pathlib.Path` (https://docs.python.org/3/library/pathlib.html)

2022-04-10 19:56 UTC, llirrikk commented on images/imager.py
> +        offset = self._draw_text(side_text, self.font_downer, self.fill_downer, offset)
Если `text_title` состоит всего из одной строчки, то `offset` надо прибавлять, а не инициализировать заново, потому что QR код заслоняет собой текст

2022-04-10 19:56 UTC, llirrikk commented on images/imager.py
> +            self.draw_text = ImageDraw.Draw(self.image)
Предлагаю засунуть все пути в структуру и инициализировать ее при объявлении класса (в конструкторе например)

2022-04-10 19:56 UTC, llirrikk commented on images/imager.py
> +        self._draw_text_news(title_text, side_text, url)
Нашел в ОРИОКС новость с самым длинным заголовком (https://orioks.miet.ru/main/view-news?id=279). Текст выходит за границы картинки

2022-04-10 19:56 UTC, llirrikk commented on images/imager.py
> +        self._draw_text_news(title_text, side_text, url)
Предлагаю итеративно уменьшать размер текста до тех пор, пока он не будет влезать в картинку

2022-04-10 19:56 UTC, llirrikk commented on images/imager.py
> +        self._draw_text_marks(title_text, mark_change_text, side_text)
Покопался у себя и нашел дисциплину с названием `Метрология, стандартизация и сертификация в инфокоммуникациях: Методы и средства измерения в телекоммуникационных системах`. Она не влезает нормально в картинку :(
Предлагаю так же как и с новостью уменьшать размер текста

2022-04-10 20:02 UTC, llirrikk commented
@Whom-m0rty, посмотри мой коммит с исправлениями всего, что мне не понравилось - b5e57864b7540044a8ccd5c907e3979892799826

2022-04-10 20:05 UTC, Whom-m0rty commented
Мне ещё учиться и учиться :)

2022-04-10 20:09 UTC, llirrikk commented
Все и так круто на самом деле. Это скорее придирки

2022-04-10 20:12 UTC, Whom-m0rty commented
Истинна рождается в спорах. 

Хороший код - в придирках

А если серьезно, то я получил большой опыт в работе с командой, спасибо за хорошие советы и критику, думаю, сможем сработаться ещё :)

2022-04-10 20:13 UTC, llirrikk commented
Может у тебя есть замечания какие-то, или я могу объединять это?

2022-04-12 04:23 UTC, Whom-m0rty commented
Думаю, что замечаний нет, спасибо :)

2022-04-13 22:38 UTC, llirrikk commented
переезжаем: https://github.com/orioks-monitoring/bot/pull/17

2022-04-13 22:38 UTC, closed without merging